# Generated by Django 3.0.3 on 2020-03-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('nom_usu', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idMonto', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(verbose_name='monto')),
                ('num_instrum', models.IntegerField(verbose_name='Numero de instrumento de pago')),
                ('tipo_inst', models.CharField(max_length=20, verbose_name='Tipo de Instrumento')),
                ('divisas', models.CharField(max_length=10, verbose_name='Divisas a utilzar')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prove', models.AutoField(primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=10, verbose_name='RIF')),
                ('nom_prove', models.CharField(max_length=20, verbose_name='Nombre del Proveedor')),
                ('direc', models.CharField(max_length=30, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zonas', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=30, verbose_name='Zona')),
                ('horas', models.CharField(max_length=6, verbose_name='Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12, verbose_name='Contraseña')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('nom_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=30, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripcion')),
                ('costo', models.IntegerField(verbose_name='Costo')),
                ('tipo_pro', models.CharField(max_length=15, verbose_name='Tipo de Productos')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('id_prove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Licores',
            fields=[
                ('id_lico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_lico', models.CharField(max_length=10, verbose_name='Tipo de Licor')),
                ('grados', models.IntegerField(verbose_name='Grados')),
                ('region', models.CharField(max_length=10, verbose_name='Region')),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_fac', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_fac', models.DateField(verbose_name='Fecha de Factura')),
                ('descuento', models.IntegerField(verbose_name='Descuento')),
                ('monto_fac', models.IntegerField(verbose_name='Monto de la Factura')),
                ('monto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula1', models.CharField(max_length=12, verbose_name='Cedula')),
                ('fecha2', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('cuenta', models.CharField(max_length=20, verbose_name='Cuenta')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12, verbose_name='Cedula')),
                ('fecha', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('tlf', models.CharField(max_length=12, verbose_name='Telefono')),
                ('membresia', models.BooleanField(default=False, verbose_name='Membresia')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuarios')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Zonas')),
            ],
        ),
    ]
