# Generated by Django 3.0.2 on 2020-01-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Direcciones',
            fields=[
                ('id_direct', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID Direccion')),
                ('zona', models.CharField(max_length=30, verbose_name='Zona')),
            ],
        ),
    ]
