# Generated by Django 3.0.2 on 2020-01-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=12, verbose_name='Cedula')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('fecha', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('tlf', models.CharField(max_length=12, verbose_name='Telefono')),
                ('memembresia', models.BooleanField(default=False, verbose_name='Membresia')),
                ('zona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.ID_Direcciones')),
            ],
        ),
    ]
