# Generated by Django 3.0.3 on 2020-02-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=12, verbose_name='Cedula')),
                ('fecha2', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('cuenta', models.CharField(max_length=20, verbose_name='Cuenta')),
            ],
        ),
    ]
