# Generated by Django 3.0.2 on 2020-01-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_tabla_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_cliente',
            old_name='memembresia',
            new_name='membresia',
        ),
    ]
