# Generated by Django 3.0.3 on 2020-03-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20200305_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nom_prove',
            new_name='id_prove',
        ),
    ]
