# Generated by Django 3.0.3 on 2020-03-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20200208_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Zonas'),
        ),
        migrations.AlterField(
            model_name='zonas',
            name='id_zonas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
