# Generated by Django 3.0.2 on 2020-02-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20200129_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Zonas',
            fields=[
                ('id_zonas', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID Zonas')),
                ('zona', models.CharField(max_length=30, verbose_name='Zona')),
            ],
        ),
        migrations.AlterField(
            model_name='tabla_cliente',
            name='zona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.ID_Zonas'),
        ),
        migrations.DeleteModel(
            name='ID_Direcciones',
        ),
    ]
