# Generated by Django 3.0.3 on 2020-03-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_auto_20200304_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonas',
            name='id_zonas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
