# Generated by Django 3.0.3 on 2020-03-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20200304_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='zona',
            new_name='zona1',
        ),
    ]
